### ISSUE TITLE
Add Collection::add_many() method.

### ISSUE THREAD

**Issue by shazahm1** [iron-bound-designs/IronBound-DB#14]
How open are you for pull requests?

I would like a `Collection::add_many()` method to compliment the Collection::add()`  method. Something like this:

```php
	/**
	 * @param array $elements
	 * @param Model $model
	 *
	 * @return bool
	 */
	public function add_many( array $elements, Model $model ) {

		foreach ( $elements as $element ) {

			$this->add( $model->fill( (array) $element ) );
		}

		return TRUE;
	}
```

I managed to "add" it by extending a couple IronBound classes such as Collection, HasMany and FluentQuery overriding methods methods which init an instance of Collection to use mine version which simply contains the method above.

It is quite the rube goldberg but is the only way I could think of adding support without editing the library directly. Which, I'd like to avoid. Now that I've done it, it really would have been far simpler to add this the the Collection class and be done with it :)

I think either way would introduce maintenance burden when updating your library.

**Comment by shazahm1** [comment]
Oh, btw, I am currently working add adding REST API support to my plugin, https://github.com/Connections-Business-Directory/Connections

I've been wanting to build something like this to replace much what I have with a base database abstraction layer when I stumbled across your work after reading Pippins article.

Basically I'm going to base the REST API codebase on this ORM and require php5.3 for REST support leaving the "old" codebase for queries and such behind for backward compatibility. So hopefully I''l be well positioned when WP.org finally drop support for php5.2.

**Comment by TimothyBJacobs** [comment]
Hey @shazahm1,

Thanks for opening an issue, send over a PR with some unit tests and I'll take a look.

Not all elements in a collection, however, extend `Model`. So you'll need to make use of the `Saver` class.

Something like.

```php
public function add_many( array $elements ) {

	foreach ( $elements as $element ) {
		$this->add( $this->saver->make_model( $element ) );
	}

	return TRUE;
}
```

However, why are you opting to pass an array of attributes instead of Model's directly?

-----

Very cool. I'd love to see what you end up doing with integrating the ORM and the REST endpoints. I've been meaning to write a package that would make adding REST endpoints for an IronBound DB project very simple, but have been caught up with work.

**Comment by shazahm1** [comment]
Thanks, I send a PR.

The reasoning is that the form I use to collect data, for example addresses, allow _n_-number of address to be submitted. I do the same with email, phone, IM, social networks and so on... so this is mostly a convenience function saving me to have to write a many foreach statements within separate methods within my "main" model. Basically this one small method reduces quite a bit of code redundancy.

Thanks for the code tip! This ORM really stretches my currently abilities so I am struggling a little. Do you have any plugins available using this I can use as reference? What I have been using is your old blog post, the readme.md and the unit tests as examples . But more practical examples would be tremendously helpful.
<hr>
I wasn't really planning on extending the ORM to support REST endpoints, my plan was to use this in place of my current code base to manage entries. But, that is an interesting idea which I may pursue. Do you have some bullet point thoughts on what you were envisioning for implementation?

I am considering on automagically registering REST endpoints for the ORM for managing tables. Perhaps automagically registering endpoints for Models. One would still have to write the code to define the schema and the other core REST logic.
<hr>
I'll send some other separate PR requests for the Table class. It seems to me that if the Table class can create tables, it should also be able to drop and truncate tables for... Purpose, for uninstalling plugins or resetting plugin to initial state.

**Comment by TimothyBJacobs** [comment]
Could you share a snippet of what you are doing? Unless you are creating hundreds of models at once the extra foreach to convert to models from attributes shouldn't be too much of a performance problem. What I'm planning on doing very shortly is adding a `create_many()` method which would be a more performant version of doing a hundred inserts. Ideally, being one insert.

Best thing to look at for reference would be [Exchange dev](https://bitbucket.org/ithemes/ithemes-exchange/src/5c5a074afc4fcc152bfa6864495e27fb4ab35571/?at=dev).

---- 

Not extending per se, but a separate package. The fillable and guarded rules mean that user input could be safely passed directly to `Model::create()`. You could also use that to handle PUT requests in a generic way. GET requests could use `Model::to_array()`. For validation, I'm using [this](https://github.com/justinrainbow/json-schema) package. I'm working on a blog post to hopefully illustrate how to integrate it with WP-API. The tricky part is how to work with relations so they can automatically be registered as routes. For example, `/transaction/5/refunds`.

----

Thanks, yeah dropping a table definitely needs to be added. It should probably be going in `IronBound\DB\Manager`.

**Comment by shazahm1** [comment]
Well, my code is very crude atm as I try to understand how this works... but, in my main Entry model I current have a function like this:

```php

	/**
	 * @param \stdClass[] $items
	 */
	public function add_addresses( array $items = array() ) {

		foreach ( $items as $row ) {

			$address = \cnSanitize::args( get_object_vars( $row ), Manager::get( 'address' )->get_column_defaults() );

			$this->address->add( new Address( $address ) );
		}
	}
```

Address (custom table) is a model setup setup as a relation to my main Entry model (custom table). I setup the relation like so in my Entry model:

```php
	/**
	 * @return HasMany
	 */
	protected function _address_relation() {

		$address = new Address();

		$relation = new HasMany( 'entry_id', get_class( $address ), $this, 'address' );
		$relation->keep_synced();

		return $relation;
	}
```
`\cnSanitize::args()` basically is just like `wp_parse_args()` but drops array key/value pairs which do not exist in the default args. So `get_object_vars( $row )` is my untrusted args and `Manager::get( 'address' )->get_column_defaults()` are my trusted args with default values in case untrusted args is missing a key/value pair.
<hr>
Ahhh, yes basically that is how I am planning on implementing the REST as far as GET/PUT requests. I just not sure how it could be a separate package without having to be tailored to the plugin but you are clearly more skilled in PHP than myself. I am learning a lot with this code even though I've spent days pounding my head against the desk (a good thing). I first tried rewriting this to be PHP5.2 compatible. I succeeded with the table manager and table/column code but hit a wall when it came to the model code. I've learned about namespaces, late static binding how to autoload this library without composer. Using Composer to manage seems to only be applicable when managing the entire WP stack (per se) on a site something most end users do not do. Perhaps reviewing IT Exchange will reveal how I should be doing this since this will be a included library in my plugin. Anyway, I'm rambling...
<hr>
Yeah, belongs in the Table Manager, but since it is marked final, I could not extend it like I could Table.
<hr>
Thanks for at least considering the PR/s when I submit them! Just remembered I have two more for new Column. 1. Date extending DateTime with type DATE and format 'Y-m-d'. 2. Timestamp extending DateTime with type TIMESTAMP.
<hr>
I'm kind  of overloading this issue. For each PR, I'll submit a new issue. Which branch should I submit against? Master seems to be more current.

**Comment by TimothyBJacobs** [comment]
Yeah, so I don't think that repeating that loop would be a killer. I'm happy to merge a patch that adds `add_many()` support, but it'd need to accept an array of already constructed models instead of doing that construction for you.

Yeah, doing this with just 5.2 is probably possible, but would probably end up being quite messy.

No problem, happy to merge those as well! The need for a `DATE` column just came up the other day actually!

Yep, master is best.

**Comment by shazahm1** [comment]
Ok, submitted a bunch of individual PR/s. If they look good, then I'll update the PR with unit test. Oh, the existing unit tests are failing against trunk, not do to any change in the PR/s. They are all relatively very basic.

**Comment by shazahm1** [comment]
Merged, closing.
