### ISSUE TITLE
Problem with DeleteConstrainer 

### ISSUE THREAD

**Issue by ludioao** [iron-bound-designs/IronBound-DB#25]
Hello, @TimothyBJacobs 
When I try to use your library, i got this error:

`Cannot use lexical variable $model as a parameter name in /vendor/ironbound/db/src/Table/Plugins/DeleteConstrainer.php on line 71`

PHP v: 7.2.5

**Comment by TimothyBJacobs** [comment]
Hey @ludioao, that problem should be fixed by, https://github.com/iron-bound-designs/IronBound-DB/commit/436f8f7781aab337175dfb3a5222e8cb51a62d58. What version of the library are you using?

**Comment by ludioao** [comment]
Thanks for reply @TimothyBJacobs .

I'm using the 2.0.0 version.

**Comment by TimothyBJacobs** [comment]
Try it on [2.1.0](https://github.com/iron-bound-designs/IronBound-DB/releases/tag/v2.1.0)

**Comment by TimothyBJacobs** [comment]
No problem, glad to hear its working! :)
